CREATE TABLE USERS
(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    BDATE VARCHAR(16) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    ABOUT VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(70) NOT NULL
);